
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a T4 template.
//     Do not modify this file manually.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KSPLocalizer
{
    public static class VersionInfo
    {
        public const string FullVersion = "1.0.0.0";
        public const int Major = 1;
        public const int Minor = 0;
        public const int Build = 0;
        public const int Revision = 0;
    }
}
